name: Question about task specifications
description: It's not clear about what the service should behave in a certain case.

title: '[Service Name] Describe your question about task specifications'
labels: [ 'type:question', 'status:waiting-for-reply' ]

body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to report a problem in the project.
        
        Please check that you've updated to the latest version of template
        and search for any existing issues, including closed ones.


  - type: textarea
    attributes:
      label: Describe your question
      description: Please state your question with enough context for us to understand.
