spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project2  # change this to your own jdbc url
    username: manager  # change this to your own username (avoid using a superuser)
    password: 123456  # change this to your own password

---

logging:
  level:
    root: off
    io.sustc: debug

---

benchmark:
  data-path: data
  student-mode: true
